/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  Fakultas: () => import('#controllers/fakultas_controller'),
  Jurusans: () => import('#controllers/jurusans_controller'),
  Login: () => import('#controllers/login_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Prints: () => import('#controllers/prints_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
}
