/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class JurusanSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'jurusanName', 'updatedAt'] as const
  $columns = JurusanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jurusanName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class KelaSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'jurusanId', 'kelasName', 'updatedAt'] as const
  $columns = KelaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jurusanId: string
  @column()
  declare kelasName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SiswaSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'dateOfBirth', 'deletedAt', 'gender', 'id', 'kelasId', 'siswaName', 'studentImage', 'updatedAt'] as const
  $columns = SiswaSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kelasId: string
  @column()
  declare siswaName: string | null
  @column()
  declare studentImage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
